### ISSUE TITLE
Official details from Victron are now available

### ISSUE THREAD

**Issue by ctschach** [keshavdv/victron-ble#17]
Finally Victron released the documentation of all the data:

https://community.victronenergy.com/storage/attachments/48745-extra-manufacturer-data-2022-12-14.pdf

who wants to work on the implementation?

**Comment by keshavdv** [comment]
I've been working on adding a few of the other device implementations based on the spec, but I've been focusing on the ones I own and can validate with.

**Comment by keshavdv** [comment]
I've asked for some clarification on byte ordering from Victron since it isn't immediately apparent when consuming the data in Python

**Comment by mpvader** [comment]
Hey @keshavdv was that answered?

**Comment by keshavdv** [comment]
Unfortunately, I haven't heard back yet.
