### ISSUE TITLE
read function doesn't work on rPi 4

### ISSUE THREAD

**Issue by pioneersfx** [keshavdv/victron-ble#54]
**Describe the bug**
I installed the script on my rPi4 and got the scan-utility working like a charm. I then tried to use the read-function to retrieve values from a smart shunt. The script starts but never gives back any values and just seems to work forever until I abort manually. Instead of an ID, I got the mac-address from the app and inserted them into the command like this:
`victron-ble read "aabbccddff@key"`
I'm not sure, what I'm doing wrong here. I tried this on two different PIs to eventually use the command via exec in NodeRed. ATM I can't get it to work in the terminal though. Is something off with my syntax? Do I have to pair the victron devices with the rPi once before being able to obtain the data?

**Desktop (please complete the following information):**
 - OS: Bullseye on Raspberry Pi

**Comment by Maxime-Bru** [comment]
Hello!
I have the same issue. Have someone (@pioneersfx ?) managed to solve this problem?
